### ISSUE TITLE
Please consider renaming this plugin

### ISSUE THREAD

**Issue by Conan-Kudo** [osbuild/koji-osbuild#117]
Would you please consider renaming this plugin to `koji-osbuild-composer`?

This plugin doesn't actually add osbuild support to Koji, it adds support for communicating to the composer service instead. The diagram calls this plugin `osbuild-composer-koji`, which is probably a more accurate name for this (though I don't like `-koji` at the end...).

Plus, calling this `koji-osbuild` means that a future plugin that actually uses osbuild directly would conflict with this plugin.

**Comment by ondrejbudai** [comment]
I see your point. On the other hand, a plugin for just calling osbuild directly doesn't exist yet, and there's no certainty that it will ever exist. Thus, it's not something immediately concerning for me, and I would rather spend time on different areas of the project. I propose revisiting this when there's such a plugin, so we don't create extra work that might not be ever needed.

**Comment by Conan-Kudo** [comment]
I was actually asked to write one, which is why I asked about renaming this one.

**Comment by ondrejbudai** [comment]
Ah, good to know! I wonder how we can cooperate more closely.

Such a plugin needs to be able to generate osbuild manifests (which means resolving dependencies, ostree commits, container refs etc). This duplicates a lot of code that's already existing in the upper layer of the image builder stack. We can also offer a production-grade composer instance, which significantly simplifies the deployment. Additionally, the image builder stack can offer some extra features like direct uploading to public clouds, which helps quite a lot with a proper CI/CD process.

**Comment by Conan-Kudo** [comment]
The problem with your stack is that it's _too_ opinionated. None of the CentOS SIGs interested in it can use it because it's restricted to what is available in the Image Builder infrastructure, which means it can't use any SIG content.

It also is completely incompatible with the CentOS Build System infrastructure as well as most Koji deployments due to its reliance on Kerberos authentication.

The dependency resolving thing is going to be a pain for sure, it's unfortunate that osbuild doesn't support doing this internally like other image build tools do. I have not yet figured out a solution for that problem, but it might wind up being that the plugin will have to generate the JSON on the fly and rewrite the inputs. I already know that I need to rewrite the repo sources for the Koji plugin because we need it to be constricted to what Koji sets up as the input repo.

**Comment by teg** [comment]
> The problem with your stack is that it's too opinionated.

If there is interest in making this work we can definitely figure this out.

> it can't use any SIG content or architectures that aren't supported by the Image Builder infrastructure.

This should not be a problem, we got this working for both RHEL and Fedora.

> It also is completely incompatible with the CentOS Community Build System infrastructure as well as most Koji deployments due to its reliance on Kerberos authentication.

Is this about mTLS support? Sounds like it should be easy to add.

**Comment by Conan-Kudo** [comment]
Well, the Alternative Images SIG gave up just recently on having Image Builder for producing OSTree type images because of these problems. The Automotive SIG gave up a while ago and tells people to build locally on their computers using `osbuild` manually. The Hyperscale SIG can't use this because Image Builder doesn't support Btrfs (which also causes problems for Fedora too).

**Comment by Conan-Kudo** [comment]
Well, the Alternative Images SIG gave up just recently on having Image Builder for producing OSTree type images because of these problems. The Automotive SIG gave up a while ago and tells people to build locally on their computers using `osbuild` manually. The Hyperscale SIG can't use this because Image Builder doesn't support Btrfs (which also causes problems for Fedora too).

And there's still the "can't access SIG or buildroot repo content from Image Builder" issue for all of them.

If these problems can be resolved, sure, let's take another look.

**Comment by ondrejbudai** [comment]
> Well, the Alternative Images SIG gave up just recently on having Image Builder for producing OSTree type images because of these problems. The Automotive SIG gave up a while ago and tells people to build locally on their computers using `osbuild` manually. The Hyperscale SIG can't use this because Image Builder doesn't support Btrfs (which also causes problems for Fedora too).

FTR, you will not solve this by using osbuild directly, there's still some work needed to be done in osbuild itself (e.g. to support subvolumes).

> And there's still the "can't access SIG or buildroot repo content from Image Builder" issue for all of them.

That's actually not true. `koji-osbuild` talks to `osbuild-composer` which accepts the repositories in an API call, see https://github.com/osbuild/osbuild-composer/blob/main/internal/cloudapi/v2/openapi.v2.yml#L742

> If these problems can be resolved, sure, let's take another look.

I think they can: mTLS should be quite simple, btrfs might be tricky because we were seeing kernel issues (see https://github.com/osbuild/osbuild/pull/1203).  I believe these are the only two unresolved blockers from your comments.

I honestly think that focusing on enhancing the current stack is a better path forward, rather than creating yet another integration tool that will bring its own problems and increase the overall maintenance.

**Comment by Conan-Kudo** [comment]
> That's actually not true. koji-osbuild talks to osbuild-composer which accepts the repositories in an API call, see https://github.com/osbuild/osbuild-composer/blob/main/internal/cloudapi/v2/openapi.v2.yml#L742

But this won't work because of the lockfile manifest thing, though...? IIRC, all of that is tightly coupled and since osbuild can't do its own dependency resolution, we can't handle refreshes in the content source properly.

**Comment by ondrejbudai** [comment]
The concept of osbuild manifests is that if you build the same manifest twice, you always get the same image (functionally; we don't care about bit to bit equality that much). Osbuild doesn't do any smart stuff, it just builds an image following a very specific recipe (well, we call it a manifest). Manifests are not meant to be written by humans, they are like machine code.

The tool for creating manifests is osbuild-composer. Koji-osbuild calls it via the [Cloud API](https://github.com/osbuild/osbuild-composer/blob/main/internal/cloudapi/v2/openapi.v2.yml). When an image is requested via this API, composer takes the repositories, fetches fresh metadata, dependency solves packages that are needed for the requested image, creates a manifest and passes it to osbuild to build the actual image. When the image build is done, it uploads it somewhere. In case of koji, it always uploads it back to koji, but it can also simultaneously upload it to S3, EC2, Azure or GCP. OCI and VSphere is also available in the code, but not exposed in the API.

The manifest generation is currently implemented in Go in a Go package inside osbuild-composer, but we will be soon extracting it and putting in a separate repository. You can control the manifest generation process using many customizations that we offer. You can modify the package set, partitioning, files in `/etc` (will be merged in a week or so), kernel options (not sure if exposed currently) and more. We are more than happy to hear more suggestions.

The nice thing about this model is that we test the manifest generation in our upstream CI. On every commit of osbuild-composer, we build all these images and boot test them in their target environment. Even though there are some gaps (alt-arch testing), this makes osbuild-composer quite reliable.

**Comment by supakeen** [comment]
After some chat about this in the team (I had revived this issue due to it being related to work-for-Fedora) I'll be closing this issue. The name, while not the best, is still related to the tooling and it has become load-bearing.
