### ISSUE TITLE
builder: return value inconsistent 

### ISSUE THREAD

**Issue by gicmo** [osbuild/koji-osbuild#15]
The json that is returned is not well structured right now. I think it would be better to have something like:
```
        result = {
            "status": status.status, /* ComposeResult.status */
            "osbuild": {
                "id": cid /* osbuild-composer compose id */
            },
            "koji": {
                "build": bid /* build id return via CGInitBuild, or CGImport */
            }
        }
```
I am tempted to also include the composer URL in the `osbuild` object, so that clients can check the compose details if they want to. Not sure about the level of nesting.

**Comment by gicmo** [comment]
NB: kojid returns a plain text string for image builds: https://pagure.io/koji/blob/master/f/builder/kojid#_2606

**Comment by teg** [comment]
I like including the URL, just as you did.
